# Generated by Django 5.2.6 on 2025-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_homepagetext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagetext',
            old_name='text',
            new_name='contacts',
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='faculty',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='international',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='programs',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='teachers',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
